"use client"

import * as React from "react"
import {
  Download,
  ExternalLink,
  FileCode,
  FileImage,
  FileJson,
  FileText,
  Info,
  Search,
  Sliders,
  Trash2
} from "lucide-react"
import { cn } from "@/lib/utils"

interface GeneratedFile {
  name: string
  type: "pdf" | "json" | "png" | "csv"
  size: string
  createdTime: string
  agent: string
  summary: string
}

const initialFiles: GeneratedFile[] = [
  {
    name: "user_synthesis_report.pdf",
    type: "pdf",
    size: "242 KB",
    createdTime: "4m ago",
    agent: "Orion-Summarizer",
    summary: "Comprehensive analytical report summarizing customer satisfaction scores, feature requests, and churn risks compiled from 1,200 raw feedback entries."
  },
  {
    name: "workspace_dependency_tree.json",
    type: "json",
    size: "1.2 MB",
    createdTime: "12m ago",
    agent: "Dev-Assistant-V4",
    summary: "Serialized JSON map outlining the direct and indirect dependency trees of the active node workspace package directories."
  },
  {
    name: "agent_flowchart_v4.png",
    type: "png",
    size: "3.4 MB",
    createdTime: "1h ago",
    agent: "Auto-CodeGen Helper",
    summary: "Visual schema image outlining the nested Bezier links between the manual trigger, core summarizer agent, and database outputs."
  },
  {
    name: "billing_invoices_consolidated.csv",
    type: "csv",
    size: "18 KB",
    createdTime: "4h ago",
    agent: "Billing-Collector",
    summary: "Tabulated comma-separated database values tracking invoice identifiers, tier conversions, and active token usages for the billing workspace."
  },
  {
    name: "security_vulnerability_audit.json",
    type: "json",
    size: "45 KB",
    createdTime: "1d ago",
    agent: "Guardrail-Sentinel",
    summary: "Detailed vulnerability audit report marking security packages flags, deprecated client packages, and suggestions for packages upgrade."
  }
]

export default function OutputsPage() {
  const [files, setFiles] = React.useState<GeneratedFile[]>(initialFiles)
  const [search, setSearch] = React.useState("")
  const [selectedType, setSelectedType] = React.useState<"All" | "pdf" | "json" | "png" | "csv">("All")
  const [selectedFile, setSelectedFile] = React.useState<GeneratedFile | null>(initialFiles[0])

  const handleDeleteFile = (fileName: string) => {
    const updatedFiles = files.filter(f => f.name !== fileName)
    setFiles(updatedFiles)
    if (selectedFile?.name === fileName) {
      setSelectedFile(updatedFiles[0] || null)
    }
  }

  const getFileIcon = (type: GeneratedFile["type"]) => {
    switch (type) {
      case "pdf":
        return <FileText className="size-8 text-rose-500" />
      case "json":
        return <FileJson className="size-8 text-amber-500" />
      case "png":
        return <FileImage className="size-8 text-blue-500" />
      case "csv":
        return <FileCode className="size-8 text-emerald-500" />
    }
  }

  const filteredFiles = files.filter(f => {
    const matchesSearch = f.name.toLowerCase().includes(search.toLowerCase()) || f.agent.toLowerCase().includes(search.toLowerCase())
    if (selectedType === "All") return matchesSearch
    return f.type === selectedType && matchesSearch
  })

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Page Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Artifact Outputs</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Inspect, download, and review files and assets generated by agent pipelines.
        </p>
      </div>

      {/* Control Filter Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl border border-border/50 bg-card/45 backdrop-blur-md">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search artifacts by file name or agent..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-xs bg-background/50 border border-border rounded-lg outline-hidden focus:border-primary focus:ring-2 focus:ring-primary/15 transition-all"
          />
        </div>

        <div className="flex items-center gap-1.5 bg-muted/40 p-0.5 rounded-lg border text-xs font-medium text-muted-foreground">
          {(["All", "pdf", "json", "png", "csv"] as const).map((t) => (
            <button
              key={t}
              onClick={() => setSelectedType(t)}
              className={cn(
                "px-3 py-1 rounded-md transition-all cursor-pointer uppercase",
                selectedType === t ? "bg-background text-foreground shadow-xs" : "hover:text-foreground"
              )}
            >
              {t}
            </button>
          ))}
        </div>
      </div>

      {/* Workspace Area: Grid + Preview Sidebar */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        {/* Left Column (Files List/Grid) */}
        <div className="lg:col-span-2 space-y-3">
          {filteredFiles.length > 0 ? (
            filteredFiles.map((file) => {
              const isSelected = selectedFile?.name === file.name
              return (
                <div
                  key={file.name}
                  onClick={() => setSelectedFile(file)}
                  className={cn(
                    "border p-4 rounded-xl shadow-xs transition-all cursor-pointer duration-200 flex items-center justify-between gap-4",
                    isSelected
                      ? "bg-card border-primary/50 ring-2 ring-primary/10 dark:bg-card/40"
                      : "bg-card/40 border-border/50 hover:border-border hover:bg-card/65"
                  )}
                >
                  <div className="flex items-center gap-3.5 min-w-0">
                    <div className="shrink-0 p-2 bg-background border border-border/50 rounded-lg">
                      {getFileIcon(file.type)}
                    </div>
                    <div className="min-w-0">
                      <h3 className="text-xs font-bold text-foreground truncate">{file.name}</h3>
                      <p className="text-[10px] text-muted-foreground mt-0.5 font-medium">
                        Size: {file.size} • Created: {file.createdTime}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 shrink-0">
                    <span className="hidden sm:inline-block text-[10px] font-semibold bg-muted/70 text-muted-foreground px-2 py-0.5 rounded-full border border-border/20">
                      {file.agent}
                    </span>
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleDeleteFile(file.name)
                      }}
                      className="p-1.5 rounded-lg hover:bg-rose-500/10 text-muted-foreground hover:text-rose-500 transition-all cursor-pointer"
                      title="Delete Output File"
                    >
                      <Trash2 className="size-4" />
                    </button>
                  </div>
                </div>
              )
            })
          ) : (
            <div className="border border-dashed border-border py-12 text-center text-muted-foreground rounded-xl bg-card/10">
              No generated outputs found.
            </div>
          )}
        </div>

        {/* Right Column (File Preview Panel) */}
        <div className="border border-border/50 bg-card/45 backdrop-blur-md p-6 rounded-xl flex flex-col justify-between shadow-xs min-h-[360px]">
          {selectedFile ? (
            <div className="space-y-5 flex-1 flex flex-col justify-between">
              <div className="space-y-4">
                <div className="flex justify-between items-start border-b border-border/50 pb-3">
                  <div>
                    <span className="text-[9px] uppercase font-bold text-primary tracking-wider font-mono">
                      File Metadata
                    </span>
                    <h3 className="text-sm font-bold text-foreground mt-0.5 truncate max-w-[180px]">
                      {selectedFile.name}
                    </h3>
                  </div>
                  <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-md bg-muted border text-muted-foreground">
                    {selectedFile.type}
                  </span>
                </div>

                <div className="space-y-3.5">
                  <div className="grid grid-cols-2 gap-4 text-xs font-medium border-b border-border/30 pb-3.5">
                    <div>
                      <span className="text-[9px] text-muted-foreground block font-semibold uppercase">File Size</span>
                      <span className="text-foreground mt-0.5 block">{selectedFile.size}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-muted-foreground block font-semibold uppercase">Creator Agent</span>
                      <span className="text-foreground mt-0.5 block truncate">{selectedFile.agent}</span>
                    </div>
                  </div>

                  <div>
                    <span className="text-[9px] text-muted-foreground block font-semibold uppercase">Generated Log Summary</span>
                    <p className="text-xs text-foreground/80 mt-1.5 leading-relaxed bg-background/40 p-3 rounded-lg border border-border/40 font-medium">
                      {selectedFile.summary}
                    </p>
                  </div>
                </div>
              </div>

              {/* Action Buttons inside Preview */}
              <div className="grid grid-cols-2 gap-3 pt-5 border-t border-border/50 mt-4">
                <button className="flex items-center justify-center gap-1.5 h-9 rounded-lg text-xs font-semibold hover:bg-muted transition-all border border-border bg-background cursor-pointer">
                  <ExternalLink className="size-3.5" />
                  Preview File
                </button>
                <button className="flex items-center justify-center gap-1.5 h-9 rounded-lg text-xs font-semibold text-primary-foreground bg-primary hover:bg-primary/95 transition-all cursor-pointer shadow-xs shadow-primary/10">
                  <Download className="size-3.5" />
                  Download
                </button>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center py-12 text-muted-foreground">
              <Info className="size-8 text-muted-foreground/50 mb-3" />
              <p className="text-xs">Select a generated output file to review metadata and compile log summaries.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
