import fs from 'fs';
import path from 'path';
import { ensureDir } from '../../utils/fs.js';
import { logger } from './logger.js';

export interface ReportData {
  // Task info
  taskName: string;
  goal: string;
  startTime: number;
  endTime: number;

  // Results
  success: boolean;
  totalSteps: number;
  successfulSteps: number;
  failedSteps: number;
  recoveredSteps: number;

  // Steps detail
  steps: ReportStep[];

  // Performance
  tokensUsed: number;
  estimatedCost: number;

  // Output
  flowPath?: string;
  outputFiles?: string[];
  extractedItems?: number;

  // Errors
  errors: string[];
}

export interface ReportStep {
  id: number;
  tool: string;
  params: Record<string, any>;
  status: 'success' | 'failed' | 'recovered';
  duration: number;
  error?: string;
  recoveryStrategy?: string;
}

export class ReportGenerator {
  /**
   * Generate Markdown execution report
   */
  generateMarkdown(data: ReportData): string {
    const duration = data.endTime - data.startTime;
    const durationStr = this.formatDuration(duration);
    const costStr = `$${data.estimatedCost.toFixed(4)}`;

    let md = `# Orbiter Execution Report

## Summary

| Metric | Value |
|--------|-------|
| Task | ${data.taskName} |
| Status | ${data.success ? '✅ Success' : '⚠️ Completed with errors'} |
| Start Time | ${new Date(data.startTime).toLocaleString()} |
| Duration | ${durationStr} |
| Total Steps | ${data.totalSteps} |
| Successful | ${data.successfulSteps} |
| Failed | ${data.failedSteps} |
| Recovered | ${data.recoveredSteps} |
| LLM Tokens | ${data.tokensUsed.toLocaleString()} |
| Estimated Cost | ${costStr} |

## Goal

> ${data.goal}

## Step Details

| # | Tool | Status | Duration | Notes |
|---|------|--------|----------|-------|
`;

    for (const step of data.steps) {
      const statusIcon =
        step.status === 'success'
          ? '✓'
          : step.status === 'recovered'
            ? '↻'
            : '✖';

      const notes = step.error
        ? `Error: ${step.error}`
        : step.recoveryStrategy
          ? `Recovered: ${step.recoveryStrategy}`
          : '-';

      md += `| ${step.id} | ${step.tool} | ${statusIcon} ${step.status} | ${step.duration}ms | ${notes} |\n`;
    }

    if (data.outputFiles && data.outputFiles.length > 0) {
      md += `\n## Output Files\n\n`;
      for (const file of data.outputFiles) {
        md += `- \`${file}\`\n`;
      }
    }

    if (data.extractedItems) {
      md += `\n## Extracted Data\n\n`;
      md += `Total items extracted: **${data.extractedItems}**\n`;
    }

    if (data.errors.length > 0) {
      md += `\n## Errors\n\n`;
      for (const error of data.errors) {
        md += `- ${error}\n`;
      }
    }

    if (data.flowPath) {
      md += `\n## Recorded Flow\n\n`;
      md += `Flow saved to: \`${data.flowPath}\`\n\n`;
      md += `Replay command:\n\`\`\`bash\norbiter replay ${data.flowPath}\n\`\`\`\n`;
    }

    md += `\n---\n*Generated by Orbiter v1.0.0*\n`;

    return md;
  }

  /**
   * Generate JSON report
   */
  generateJson(data: ReportData): string {
    return JSON.stringify(
      {
        ...data,
        generatedAt: Date.now(),
        orbiterVersion: '1.0.0',
      },
      null,
      2,
    );
  }

  /**
   * Save report to file
   */
  save(data: ReportData, format: 'markdown' | 'json' = 'markdown'): string {
    const reportDir = path.join(process.cwd(), 'reports');
    ensureDir(reportDir);

    const timestamp = new Date()
      .toISOString()
      .slice(0, 19)
      .replace(/[T:]/g, '-');

    const safeName = data.taskName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '-')
      .slice(0, 30);

    const ext = format === 'markdown' ? 'md' : 'json';
    const filename = `report-${safeName}-${timestamp}.${ext}`;
    const filePath = path.join(reportDir, filename);

    const content =
      format === 'markdown'
        ? this.generateMarkdown(data)
        : this.generateJson(data);

    fs.writeFileSync(filePath, content);
    logger.success(`Report saved: ${filePath}`);

    return filePath;
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;

    const mins = Math.floor(ms / 60000);
    const secs = Math.round((ms % 60000) / 1000);
    return `${mins}m ${secs}s`;
  }
}
