import { logger } from './logger.js';
import { DataRepository } from '../../memory/database/repositories/data-repository.js';

export interface ReportData {
  taskName: string;
  goal: string;
  startTime: number;
  endTime: number;

  success: boolean;
  totalSteps: number;
  successfulSteps: number;
  failedSteps: number;
  recoveredSteps: number;

  steps: ReportStep[];

  tokensUsed: number;
  estimatedCost: number;

  flowId?: string;
  outputs?: string[];
  extractedItems?: number;

  errors: string[];
}

export interface ReportStep {
  id: number;
  tool: string;
  params: Record<string, any>;
  status: 'success' | 'failed' | 'recovered';
  duration: number;
  error?: string;
  recoveryStrategy?: string;
}

export class ReportGenerator {
  generateMarkdown(data: ReportData): string {
    const duration = data.endTime - data.startTime;
    const durationStr = this.formatDuration(duration);
    const costStr = `$${data.estimatedCost.toFixed(4)}`;

    let md = `# Orbiter Execution Report

## Summary

| Metric | Value |
|--------|-------|
| Task | ${data.taskName} |
| Status | ${data.success ? '✅ Success' : '⚠️ Completed with errors'} |
| Start Time | ${new Date(data.startTime).toLocaleString()} |
| Duration | ${durationStr} |
| Total Steps | ${data.totalSteps} |
| Successful | ${data.successfulSteps} |
| Failed | ${data.failedSteps} |
| Recovered | ${data.recoveredSteps} |
| LLM Tokens | ${data.tokensUsed.toLocaleString()} |
| Estimated Cost | ${costStr} |

## Goal

> ${data.goal}

## Step Details

| # | Tool | Status | Duration | Notes |
|---|------|--------|----------|-------|
`;

    for (const step of data.steps) {
      const statusIcon =
        step.status === 'success' ? '✓' : step.status === 'recovered' ? '↻' : '✖';

      const notes = step.error
        ? `Error: ${step.error}`
        : step.recoveryStrategy
          ? `Recovered: ${step.recoveryStrategy}`
          : '-';

      md += `| ${step.id} | ${step.tool} | ${statusIcon} ${step.status} | ${step.duration}ms | ${notes} |\n`;
    }

    if (data.outputs && data.outputs.length > 0) {
      md += `\n## Saved Outputs\n\n`;
      for (const ref of data.outputs) {
        md += `- ${ref}\n`;
      }
    }

    if (data.extractedItems) {
      md += `\n## Extracted Data\n\nTotal items extracted: **${data.extractedItems}**\n`;
    }

    if (data.errors.length > 0) {
      md += `\n## Errors\n\n`;
      for (const error of data.errors) {
        md += `- ${error}\n`;
      }
    }

    if (data.flowId) {
      md += `\n## Recorded Flow\n\nFlow ID: \`${data.flowId}\`\n\n`;
      md += `Replay command:\n\`\`\`bash\norbiter replay ${data.flowId}\n\`\`\`\n`;
    }

    md += `\n---\n*Generated by Orbiter v1.0.0*\n`;
    return md;
  }

  generateJson(data: ReportData): string {
    return JSON.stringify({ ...data, generatedAt: Date.now(), orbiterVersion: '1.0.0' }, null, 2);
  }

  async save(
    data: ReportData,
    format: 'markdown' | 'json' = 'markdown',
    sessionId?: string | null,
  ): Promise<string> {
    const content = format === 'markdown' ? this.generateMarkdown(data) : this.generateJson(data);

    try {
      const repo = new DataRepository();
      const id = await repo.saveReport(sessionId ?? null, data.taskName, format, content, data);
      logger.success(`Report saved to database (report #${id})`);
      return `#${id}`;
    } catch (err) {
      logger.warn(`Failed to save report to database: ${(err as Error).message}`);
      return '';
    }
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    const mins = Math.floor(ms / 60000);
    const secs = Math.round((ms % 60000) / 1000);
    return `${mins}m ${secs}s`;
  }
}
